AWSTemplateFormatVersion: 2010-09-09
Description: Kati Demo CloudFormation

Resources:
  Katinampari:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: katin-cloudformation-ampari

  KatinSQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName : Katinjono
